name: agelapse
description: A powerful tool for creating stabilized aging timelapses.
publish_to: 'none'

version: 2.4.0+36

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  animated_bottom_navigation_bar: ^1.4.0
  archive: ^4.0.7
  async_zip: ^0.1.0
  camera: ^0.11.0
  camera_android_camerax: 0.6.7
  camera_macos: ^0.0.9
  camera_windows: ^0.2.5
  chewie: ^1.13.0
  desktop_drop: ^0.7.0
  device_info_plus: ^12.3.0
  exif_reader: ^4.1.0
  face_detection_tflite: ^4.4.1
  ffmpeg_kit_flutter_new:
    git:
      url: https://github.com/hugocornellier/ffmpeg_kit_flutter.git
      ref: 2d57062b1d57e3ee5539eeb42a9c16192f84e2d5
  file_picker: ^10.3.8
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  flutter_avif: ^3.1.0
  flutter_email_sender: ^8.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.5.0
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.2.3
  flutter_timezone: ^5.0.1
  font_awesome_flutter: ^10.12.0
  google_mlkit_pose_detection: ^0.14.0
  heif_converter: ^1.0.1
  intl: ^0.20.2
  material_symbols_icons: ^4.2892.0
  mime: ^2.0.0
  media_kit: ^1.1.11
  media_kit_video: ^2.0.1
  media_kit_libs_windows_video: ^1.0.11
  opencv_dart: ^2.1.0
  package_info_plus: ^9.0.0
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pose_detection_tflite: ^1.1.0
  provider: ^6.1.5
  saver_gallery: ^4.1.0
  sensors_plus: ^7.0.0
  share_plus: ^12.0.1
  smooth_page_indicator: ^2.0.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0
  sqlite3_flutter_libs: ^0.5.41
  timezone: ^0.10.1
  url_launcher: ^6.3.2
  vibration: ^3.1.5
  video_player: ^2.10.1
  video_player_win: ^3.2.2
  video_player_media_kit: ^2.0.0
  media_kit_libs_linux: ^1.2.1
  wakelock_plus: ^1.4.0
  wechat_assets_picker: ^10.1.0
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.3
  fake_async: ^1.3.1
  image: ^4.7.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/ghost-custom.svg
    - assets/relax.svg
    - assets/ffmpeg/windows/ffmpeg.exe
    - assets/ffmpeg/windows/LICENSE
    - assets/heic/windows/heicConverter.exe
    - assets/test_fixtures/sample_faces/
    - assets/test_fixtures/sample-avif.avif
    - assets/test_fixtures/sample-heic.HEIC
    # Font licenses (for legal compliance)
    - assets/fonts/Inter/OFL.txt
    - assets/fonts/Roboto/LICENSE.txt
    - assets/fonts/SourceSans3/OFL.txt
    - assets/fonts/Nunito/OFL.txt
    - assets/fonts/JetBrainsMono/OFL.txt

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: SourceSans3
      fonts:
        - asset: assets/fonts/SourceSans3/SourceSans3-Regular.ttf
        - asset: assets/fonts/SourceSans3/SourceSans3-Medium.ttf
          weight: 500
        - asset: assets/fonts/SourceSans3/SourceSans3-SemiBold.ttf
          weight: 600
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Variable.ttf
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.jpg"

flutter_native_splash:
  color: "#2b2b2b"
  image: assets/images/splash/logo.png
  android_12:
    color: "#2b2b2b"
    image: assets/images/splash/logo-android.png
